---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(HPTest)
```


## Constructor function

```{r myttest}
HPTest::myttest

```


## Print function

```{r print}

print_method <- getS3method("print", "Rttest")
print(print_method)

```

## Plot function

```{r plot}
HPTest::plot

```

## Example Run

```{r run}
#T-test
set.seed(32); x=rnorm(30,mean=10,sd=15)
set.seed(35); y=rnorm(30,mean=8,sd=15)
ans1=myttest(x,y,alpha=0.05,paired=FALSE)
print(ans1)
plot(ans1)

#Welch Test
set.seed(32); x=rnorm(30,mean=10,sd=5)
set.seed(35); y=rnorm(30,mean=8,sd=15)
ans2=myttest(x,y,alpha=0.05,paired=FALSE)
print(ans2)
plot(ans2)

#Paired Test
set.seed(32); x=rnorm(30,mean=10,sd=15)
set.seed(35); y = x+ rnorm(30, 5 ,4)
ans3=myttest(x,y,alpha=0.05,paired=TRUE)
print(ans3)
plot(ans3)

```

